### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [kdar/wox-dracula-theme#1]
Hello @kdar!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by kdar** [comment]
That's fine with me :+1:

**Comment by zenorocha** [comment]
Awesome!

First, you need to accept an invitation to join the organization, you should find this on your email.

**Comment by kdar** [comment]
Accepted.

**Comment by zenorocha** [comment]
Ok, now go to https://github.com/kdar/wox-dracula-theme/settings and select `Transfer`.

Then, apply this template (https://github.com/dracula/template) which includes `README`, `LICENSE`, and `.github`.

**Comment by zenorocha** [comment]
You can also rename this repo to `wox`

**Comment by kdar** [comment]
Yea, working on it.

**Comment by kdar** [comment]
Finished everything I think.

**Comment by zenorocha** [comment]
Now we're finished.

https://github.com/dracula/wox/commit/e9fc1bfda78b0f40af81b29ed67bca8de06f115c

You done the work, you deserve the credit :)

I'll get an icon and update the site now.

**Comment by zenorocha** [comment]
@kdar, can you share the instructions on how to install this theme? I need that for the website. See https://draculatheme.com/sublime/ as an example.

**Comment by kdar** [comment]
## Install manually

1. Download using the [Github .zip download](https://github.com/dracula/wox/archive/master.zip) option and unzip it.
2. Move `Dracula.xaml` to `Wox\Themes\`
3. Open up Wox by running it or hitting your global hotkey
4. Type `settings` and run `Settings, Tweak this app`
5. Go to the `Theme` tab and select `Dracula` and exit out of settings
6. Your theme is now applied.

**Comment by zenorocha** [comment]
There you go! https://draculatheme.com/wox

Thanks a lot for your help @kdar!
