### ISSUE TITLE
[BUG] "Fail to load theme Dracula, fallback to default theme" Wox Version 1.4.1196

### ISSUE THREAD

**Issue by novahreal** [kdar/wox-dracula-theme#5]
https://user-images.githubusercontent.com/64397602/104257959-72bd3580-5433-11eb-9fd6-d253211122d0.mp4

When trying to apply theme, I get the error "Fail to load theme Dracula, fallback to default theme"

**Comment by kdar** [comment]
In issue #4 this occurred as well. Do the comments in that issue help?

**Comment by novahreal** [comment]
After some digging it seems the new path for themes is \AppData\Local\Wox\app-1.4.1196\Themes

What is really strange about it is the normal \AppData\Roaming\Wox\Themes folder is where I had originally put it - new themes  put into that folder show up in the wox settings but don't actually work.  Super strange.

Thanks!
